image:
  repository: mtz.ocir.io/orasenatdpltintegration03/triton_trt_llm_rclone_commands
  tag: latest
  pullPolicy: IfNotPresent
ports:
  http: 8000
  grpc: 8001
  metrics: 8002
resources:
  requests:
    memory: "20Gi"
    gpu: "1"
  limits:
    memory: "30Gi"
    gpu: "1"
